- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    pool_dir: "/mnt/ext4/images"
    vm: u22
    vcpus: 4
    ram_mb: 8192
    net: default
    cleanup: no
    ssh_key: /home/ubuntu/.ssh/id_rsa.pub
    image_name: jammy-server-cloudimg-amd64.img
    image_url: https://cloud-images.ubuntu.com/jammy/current/{{ base_image_name }}
    image_sha: 8ae2ebcaf1320ea5b8d7003b44f2dbcb4ecad8cc53a3170e96d9ff1bbe8f78b8
    root_pass: ubuntu
    resize: 1
    selinux: no

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_pub_key: "{{ ssh_key }}"
        base_image_name: "{{ image_name }}"
        base_image_url: "{{ image_url }}"
        base_image_sha: "{{ image_sha }}"
        vm_root_pass: "{{ root_pass }}"
        vm_resize: "{{ resize }}"
        vm_selinux: "{{ selinux }}"

